const books = [
  {
    url: "https://covers.openlibrary.org/b/isbn/9780439708180-L.jpg",
    title: "Harry Potter and the Philosopher's Stone",
    author: "J.K. Rowling",
    price: 12.99,
    desc: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat. A young boy discovers he is a wizard and begins his journey at Hogwarts School of Witchcraft and Wizardry, where he makes friends, faces enemies, and uncovers a plot threatening the wizarding world.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780061935466-L.jpg",
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 10.99,
    desc: "Set in the American South during the 1930s, this Pulitzer Prize-winning novel follows young Scout Finch as her father, lawyer Atticus Finch, defends a Black man falsely accused of raping a white woman, exploring themes of racial injustice, moral growth, and compassion.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780451524935-L.jpg",
    title: "1984",
    author: "George Orwell",
    price: 9.99,
    desc: "In a totalitarian future society, Winston Smith works for the Party rewriting history. He secretly rebels against Big Brother's omnipotent rule by falling in love and seeking truth, in this chilling dystopian masterpiece about surveillance, propaganda, and the destruction of individual freedom.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780743273565-L.jpg",
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 8.99,
    desc: "Set in the Roaring Twenties, this novel follows the mysterious millionaire Jay Gatsby and his obsession with the beautiful Daisy Buchanan. Narrated by Nick Carraway, it is a profound critique of the American Dream, wealth, class, and the passage of time.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780141439518-L.jpg",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 7.99,
    desc: "The story follows Elizabeth Bennet as she navigates issues of manners, morality, education, and marriage in the society of the landed gentry of early 19th-century England. Her turbulent relationship with the proud Mr. Darcy forms the heart of this beloved classic.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780316769174-L.jpg",
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    price: 10.49,
    desc: "Told through the voice of teenager Holden Caulfield, this novel chronicles his experiences in New York City after being expelled from prep school. A landmark of American literature exploring themes of teenage angst, alienation, identity, and the loss of innocence.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780547928227-L.jpg",
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 11.99,
    desc: "Bilbo Baggins, a comfortable hobbit, is swept into an epic quest to reclaim the Lonely Mountain with a band of dwarves and the wizard Gandalf. Along the way he encounters trolls, elves, goblins, and the mysterious creature Gollum, who possesses a magical ring.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780060850524-L.jpg",
    title: "Brave New World",
    author: "Aldous Huxley",
    price: 9.49,
    desc: "Set in a futuristic World State where citizens are environmentally engineered into an intelligence-based social hierarchy, this dystopian novel questions the cost of stability and happiness. Bernard Marx seeks meaning in a world engineered to eliminate suffering and individuality.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780618640157-L.jpg",
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    price: 24.99,
    desc: "The epic tale of Frodo Baggins and his fellowship's quest to destroy the One Ring and defeat the Dark Lord Sauron. A monumental work of high fantasy that created the template for the genre, featuring richly imagined worlds, languages, and mythology.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780451526342-L.jpg",
    title: "Animal Farm",
    author: "George Orwell",
    price: 7.49,
    desc: "A group of farm animals rebel against their human farmer, hoping to create a society where the animals can be equal, free, and happy. But as the pigs gain power, the revolution's ideals are corrupted. A sharp political allegory about the rise of totalitarianism.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780743273558-L.jpg",
    title: "Romeo and Juliet",
    author: "William Shakespeare",
    price: 6.99,
    desc: "The timeless tragedy of two young star-crossed lovers whose deaths ultimately reconcile their feuding families. Set in Verona, Italy, this play explores the power of love, fate, and hatred in one of the greatest love stories ever written.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780140449136-L.jpg",
    title: "The Divine Comedy",
    author: "Dante Alighieri",
    price: 13.99,
    desc: "An epic poem in which the poet journeys through Hell, Purgatory, and Paradise guided by Virgil and Beatrice. Considered the greatest work of Italian literature and one of the greatest works of world literature, it is a profound meditation on sin, redemption, and divine love.",
    language: "Italian",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780140449266-L.jpg",
    title: "Don Quixote",
    author: "Miguel de Cervantes",
    price: 14.99,
    desc: "A middle-aged man becomes so obsessed with chivalric romances that he loses his sanity and decides to become a knight-errant. With his faithful squire Sancho Panza, he embarks on adventures across Spain in this foundational work of Western literature.",
    language: "Spanish",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780062316097-L.jpg",
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 11.49,
    desc: "A young Andalusian shepherd named Santiago travels from Spain to Egypt in search of a worldly treasure. The story is a mystical journey of self-discovery and the pursuit of one's Personal Legend, teaching that the treasure we seek is often found within ourselves.",
    language: "Portuguese",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780385490818-L.jpg",
    title: "The Handmaid's Tale",
    author: "Margaret Atwood",
    price: 12.49,
    desc: "Set in the near-future theocratic Republic of Gilead, fertile women are forced into sexual servitude. Offred, a Handmaid, recounts her daily life while desperately clinging to her humanity and plotting escape. A chilling exploration of patriarchy, religion, and resistance.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780679720201-L.jpg",
    title: "One Hundred Years of Solitude",
    author: "Gabriel García Márquez",
    price: 13.49,
    desc: "The multi-generational story of the Buendía family in the fictional town of Macondo. A landmark of magical realism and Latin American literature, this Nobel Prize-winning novel blends the mythical and mundane into an unforgettable portrait of love, obsession, and time.",
    language: "Spanish",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780684801223-L.jpg",
    title: "The Old Man and the Sea",
    author: "Ernest Hemingway",
    price: 8.49,
    desc: "An aging Cuban fisherman named Santiago battles a giant marlin far out in the Gulf Stream in this Pulitzer Prize-winning novella. A meditation on heroism, perseverance, and man's struggle against nature, it is one of Hemingway's most celebrated works.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780374528379-L.jpg",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    price: 10.99,
    desc: "A young Russian student, Raskolnikov, plans and executes the murder of a pawnbroker to test his theory that extraordinary people are above moral law. The novel follows his psychological torment and eventual redemption in one of literature's greatest explorations of guilt and morality.",
    language: "Russian",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780140449174-L.jpg",
    title: "War and Peace",
    author: "Leo Tolstoy",
    price: 16.99,
    desc: "Set during the Napoleonic Wars, this monumental novel follows five aristocratic Russian families and weaves together their personal stories with the grand sweep of history. One of the greatest achievements in world literature, exploring war, society, love, and the meaning of life.",
    language: "Russian",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780743477550-L.jpg",
    title: "Hamlet",
    author: "William Shakespeare",
    price: 6.99,
    desc: "Prince Hamlet of Denmark is visited by his father's ghost, who claims he was murdered by his brother Claudius, now king. The play follows Hamlet's quest for revenge, exploring themes of betrayal, mortality, madness, and the difficulty of action.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780553213119-L.jpg",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    price: 14.49,
    desc: "The final novel by Dostoevsky follows the Karamazov family through a parricide and its investigation, exploring themes of faith, doubt, free will, morality, and love. Considered one of the greatest novels ever written and a masterpiece of world literature.",
    language: "Russian",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780679600015-L.jpg",
    title: "Madame Bovary",
    author: "Gustave Flaubert",
    price: 9.99,
    desc: "Emma Bovary, a doctor's wife in provincial France, becomes dissatisfied with her mediocre marriage and pursues romantic fantasies through adultery and lavish spending. This groundbreaking novel is a scathing critique of bourgeois society and Romantic literary idealism.",
    language: "French",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780679722021-L.jpg",
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    price: 13.99,
    desc: "A married Russian aristocrat, Anna Karenina, enters into a scandalous love affair with the dashing Count Vronsky, leading to her eventual downfall. Running parallel is the story of Levin, whose spiritual journey gives the novel its moral and philosophical depth.",
    language: "Russian",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780064400558-L.jpg",
    title: "Charlotte's Web",
    author: "E.B. White",
    price: 7.99,
    desc: "A young pig named Wilbur is saved from slaughter by Charlotte, a spider who weaves words into her web to make Wilbur seem miraculous. A beloved children's classic about friendship, loyalty, and the cycle of life, with themes that resonate with all ages.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780679720232-L.jpg",
    title: "The Stranger",
    author: "Albert Camus",
    price: 9.49,
    desc: "Meursault, a detached French Algerian, kills an Arab man and is put on trial. The novel is less about the killing and more about Meursault's alienation from society and indifference to life, making it a cornerstone of existentialist and absurdist literature.",
    language: "French",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780140189865-L.jpg",
    title: "Siddhartha",
    author: "Hermann Hesse",
    price: 8.99,
    desc: "Set in ancient India, the novel follows Siddhartha, a young man who leaves his privileged Brahmin life to seek spiritual enlightenment. His journey through wealth, love, and asceticism eventually leads him to wisdom by the side of a river.",
    language: "German",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780062498533-L.jpg",
    title: "The Little Prince",
    author: "Antoine de Saint-Exupéry",
    price: 8.49,
    desc: "A pilot stranded in the Sahara Desert meets a young prince who has traveled from a tiny asteroid. Through their conversations, the prince shares his adventures and the lessons he has learned about love, loneliness, friendship, and what truly matters in life.",
    language: "French",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780062457530-L.jpg",
    title: "Gone with the Wind",
    author: "Margaret Mitchell",
    price: 14.99,
    desc: "Set in the American South during the Civil War and Reconstruction era, the novel centers on the headstrong Scarlett O'Hara and her tumultuous relationship with the roguish Rhett Butler. A sweeping epic of love, loss, survival, and the collapse of a civilization.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780486415871-L.jpg",
    title: "Frankenstein",
    author: "Mary Shelley",
    price: 6.99,
    desc: "Victor Frankenstein creates a creature through an unorthodox scientific experiment. When the creature is abandoned and rejected by society, it turns monstrous. This gothic novel raises profound questions about the ethics of creation, the nature of humanity, and the consequences of unchecked ambition.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780141441146-L.jpg",
    title: "Great Expectations",
    author: "Charles Dickens",
    price: 9.49,
    desc: "Young orphan Pip unexpectedly comes into a fortune from a mysterious benefactor and navigates the complexities of class, love, ambition, and identity in Victorian England. A richly drawn coming-of-age story featuring some of Dickens' most memorable characters.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780486280615-L.jpg",
    title: "Moby-Dick",
    author: "Herman Melville",
    price: 11.99,
    desc: "Captain Ahab obsessively pursues the white sperm whale Moby Dick that severed his leg, drawing the crew of the Pequod into his mad quest. An epic sea adventure that explores obsession, fate, and humanity's relationship with nature and the unknowable.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780679783268-L.jpg",
    title: "Ulysses",
    author: "James Joyce",
    price: 15.49,
    desc: "Set over one day in Dublin on June 16, 1904, the novel follows Leopold Bloom and Stephen Dedalus through the city in a structure paralleling Homer's Odyssey. A landmark of modernist literature, celebrated for its stream-of-consciousness technique and linguistic innovation.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780385737951-L.jpg",
    title: "The Fault in Our Stars",
    author: "John Green",
    price: 10.99,
    desc: "Sixteen-year-old cancer patient Hazel meets Gus at a support group and they fall deeply in love. Together they travel to Amsterdam to meet their favorite author. A heartbreaking and life-affirming story about love, loss, and the impact we have on one another.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780062409850-L.jpg",
    title: "The Kite Runner",
    author: "Khaled Hosseini",
    price: 12.49,
    desc: "Set in Afghanistan from the 1970s through the 1990s, the story follows Amir and his childhood servant Hassan. After a devastating act of betrayal, Amir spends years haunted by guilt until a chance at redemption takes him back to his war-torn homeland.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780385490436-L.jpg",
    title: "The Road",
    author: "Cormac McCarthy",
    price: 11.99,
    desc: "A father and his young son journey across the post-apocalyptic landscape of the United States, struggling for survival while maintaining their humanity. A harrowing and deeply moving novel about the bond between parent and child in the face of unimaginable horror.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780316346627-L.jpg",
    title: "Little Women",
    author: "Louisa May Alcott",
    price: 9.99,
    desc: "The March sisters — Meg, Jo, Beth, and Amy — grow up in Civil War-era New England with their mother while their father serves as a chaplain. A beloved coming-of-age story about family, love, independence, and the pursuit of dreams in 19th-century America.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780060935467-L.jpg",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    price: 14.99,
    desc: "Nobel laureate Daniel Kahneman explores the two systems that drive the way we think — System 1 is fast, intuitive, and emotional, while System 2 is slower, deliberate, and logical. A groundbreaking look at the biases and heuristics that shape human judgment and decision-making.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9781594631931-L.jpg",
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    price: 15.99,
    desc: "Yuval Noah Harari spans the whole of human history, from the Stone Age to the Silicon Age. He explores how biology and history have defined us and enhanced our understanding of what it means to be human, examining the cognitive, agricultural, and scientific revolutions.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780385544757-L.jpg",
    title: "Educated",
    author: "Tara Westover",
    price: 13.49,
    desc: "A memoir about a young girl who, kept out of school by her survivalist family, is born and raised in the mountains of Idaho. She eventually escapes and teaches herself enough to gain admission to Cambridge University, transforming her life through education.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780679745587-L.jpg",
    title: "Beloved",
    author: "Toni Morrison",
    price: 12.99,
    desc: "Set after the American Civil War, the novel follows Sethe, a formerly enslaved woman, who is haunted by the spirit of her dead daughter. A shattering exploration of the psychological trauma of slavery, love, and the struggle for freedom and identity.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780374100070-L.jpg",
    title: "The Remains of the Day",
    author: "Kazuo Ishiguro",
    price: 11.49,
    desc: "Stevens, an aging English butler, takes a rare road trip across the countryside and reflects on his years of service to a morally compromised employer. A moving meditation on duty, dignity, regret, and the life unlived — told in Ishiguro's beautifully restrained prose.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780684833392-L.jpg",
    title: "The Sun Also Rises",
    author: "Ernest Hemingway",
    price: 10.49,
    desc: "American and British expatriates travel from Paris to Pamplona to watch the running of the bulls and the bullfights. A story of the Lost Generation following World War I, exploring themes of masculinity, love, aimlessness, and disillusionment with grace and economy.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780385014500-L.jpg",
    title: "Catch-22",
    author: "Joseph Heller",
    price: 11.99,
    desc: "Set in World War II Italy, this satirical novel follows Captain John Yossarian who is desperately trying to be grounded from flying dangerous combat missions. The famous Catch-22 paradox — that one must be crazy to fly missions but sane enough to request grounding — drives this dark comedy.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780743218023-L.jpg",
    title: "Slaughterhouse-Five",
    author: "Kurt Vonnegut",
    price: 10.99,
    desc: "Billy Pilgrim, a WWII veteran, becomes 'unstuck in time,' bouncing between his past, present, and future experiences including the firebombing of Dresden. A postmodern classic blending science fiction with a deeply humane anti-war message.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780156628709-L.jpg",
    title: "Invisible Man",
    author: "Ralph Ellison",
    price: 12.49,
    desc: "An unnamed Black narrator recounts his life in the American South and New York City, struggling for identity and recognition in a white-dominated society. A complex and visionary novel exploring race, identity, and the contradictions of American democracy.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780060763091-L.jpg",
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    price: 8.99,
    desc: "Set against the backdrop of the French Revolution, this novel follows Charles Darnay and Sydney Carton, both in love with Lucie Manette. A sweeping story of love, sacrifice, and resurrection, opening with the immortal line about the best and worst of times.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780582414273-L.jpg",
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    price: 9.99,
    desc: "The story of Okonkwo, a respected warrior in the Igbo community of Umuofia in Nigeria, and his tragic downfall as British colonialism and Christian missionaries upend the traditional Igbo society. A landmark of African literature and a powerful exploration of culture clash.",
    language: "English",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780374528348-L.jpg",
    title: "In Search of Lost Time",
    author: "Marcel Proust",
    price: 18.99,
    desc: "A monumental seven-volume novel that begins with the narrator's memories triggered by the taste of a madeleine dipped in tea. A profound meditation on memory, time, art, and society in Belle Époque France, it is one of the most celebrated works of 20th-century literature.",
    language: "French",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780374527280-L.jpg",
    title: "The Trial",
    author: "Franz Kafka",
    price: 9.99,
    desc: "Josef K. is arrested one morning without being told what crime he has committed. His desperate and surreal attempts to discover the charges and defend himself against an invisible, impenetrable justice system make this one of literature's most powerful allegories of bureaucracy and alienation.",
    language: "German",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780140445046-L.jpg",
    title: "The Odyssey",
    author: "Homer",
    price: 8.99,
    desc: "The epic poem recounting the decade-long journey of Odysseus as he tries to return home to Ithaca after the fall of Troy, facing monsters, gods, and temptations along the way. One of the oldest and most influential works of Western literature.",
    language: "Greek",
  },
  {
    url: "https://covers.openlibrary.org/b/isbn/9780316346627-L.jpg",
    title: "Rebecca",
    author: "Daphne du Maurier",
    price: 10.49,
    desc: "A young woman marries wealthy widower Maxim de Winter and moves into his imposing estate, Manderley. She is haunted by the memory of Maxim's first wife, the beautiful and enigmatic Rebecca. A masterpiece of gothic suspense about jealousy, identity, and dark secrets.",
    language: "English",
  },
];

module.exports = books;
